name: EnchantMagicPack
version: ${project.version}
main: me.hsgamer.enchantmagicpack.EnchantMagicPack
depend: [FabledEnchants]
softdepend: [Fabled]
authors: [HSGamer]
description: A magic pack for EnchantmentAPI
api-version: 1.17