package me.hsgamer.enchantmagicpack.utils;

import org.bukkit.Material;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ToolsUtils {
    public static List<Material> PICKAXES_BLOCKS = new ArrayList<>(Arrays.asList(
            Material.DIAMOND_BLOCK,
            Material.GOLD_BLOCK,
            Material.REDSTONE_BLOCK,
            Material.EMERALD_BLOCK,
            Material.COAL_BLOCK,
            Material.IRON_BLOCK,
            Material.LAPIS_BLOCK,
            Material.DIAMOND_ORE,
            Material.GOLD_ORE,
            Material.REDSTONE_ORE,
            Material.EMERALD_ORE,
            Material.COAL_ORE,
            Material.IRON_ORE,
            Material.LAPIS_ORE,
            Material.ICE,
            Material.FROSTED_ICE,
            Material.PACKED_ICE,
            Material.ANVIL,
            Material.BREWING_STAND,
            Material.CAULDRON,
            Material.IRON_FENCE,
            Material.IRON_DOOR_BLOCK,
            Material.IRON_TRAPDOOR,
            Material.HOPPER,
            Material.GOLD_PLATE,
            Material.IRON_PLATE,
            Material.STONE_PLATE,
            Material.BLACK_SHULKER_BOX,
            Material.BLUE_SHULKER_BOX,
            Material.BROWN_SHULKER_BOX,
            Material.CYAN_SHULKER_BOX,
            Material.GRAY_SHULKER_BOX,
            Material.GREEN_SHULKER_BOX,
            Material.LIGHT_BLUE_SHULKER_BOX,
            Material.LIME_SHULKER_BOX,
            Material.MAGENTA_SHULKER_BOX,
            Material.ORANGE_SHULKER_BOX,
            Material.SILVER_SHULKER_BOX,
            Material.PINK_SHULKER_BOX,
            Material.PURPLE_SHULKER_BOX,
            Material.RED_SHULKER_BOX,
            Material.WHITE_SHULKER_BOX,
            Material.YELLOW_SHULKER_BOX,
            Material.RAILS,
            Material.ACTIVATOR_RAIL,
            Material.DETECTOR_RAIL,
            Material.POWERED_RAIL,
            Material.QUARTZ_BLOCK,
            Material.CLAY_BRICK,
            Material.NETHER_BRICK,
            Material.RED_NETHER_BRICK,
            Material.SMOOTH_BRICK,
            Material.END_BRICKS,
            Material.COBBLESTONE,
            Material.COBBLE_WALL,
            Material.CONCRETE,
            Material.PRISMARINE,
            Material.DISPENSER,
            Material.DROPPER,
            Material.ENCHANTMENT_TABLE,
            Material.ENDER_STONE,
            Material.ENDER_CHEST,
            Material.FURNACE,
            Material.BLACK_GLAZED_TERRACOTTA,
            Material.BLUE_GLAZED_TERRACOTTA,
            Material.BROWN_GLAZED_TERRACOTTA,
            Material.CYAN_GLAZED_TERRACOTTA,
            Material.GRAY_GLAZED_TERRACOTTA,
            Material.GREEN_GLAZED_TERRACOTTA,
            Material.LIGHT_BLUE_GLAZED_TERRACOTTA,
            Material.LIME_GLAZED_TERRACOTTA,
            Material.MAGENTA_GLAZED_TERRACOTTA,
            Material.ORANGE_GLAZED_TERRACOTTA,
            Material.PINK_GLAZED_TERRACOTTA,
            Material.PURPLE_GLAZED_TERRACOTTA,
            Material.RED_GLAZED_TERRACOTTA,
            Material.SILVER_GLAZED_TERRACOTTA,
            Material.WHITE_GLAZED_TERRACOTTA,
            Material.YELLOW_GLAZED_TERRACOTTA,
            Material.HARD_CLAY,
            Material.STAINED_CLAY,
            Material.MOB_SPAWNER,
            Material.MOSSY_COBBLESTONE,
            Material.NETHER_BRICK,
            Material.RED_NETHER_BRICK,
            Material.NETHER_BRICK_STAIRS,
            Material.QUARTZ_ORE,
            Material.NETHERRACK,
            Material.RED_SANDSTONE,
            Material.STONE_SLAB2,
            Material.SANDSTONE,
            Material.STEP,
            Material.PURPUR_SLAB,
            Material.DOUBLE_STEP,
            Material.PURPUR_DOUBLE_SLAB,
            Material.DOUBLE_STONE_SLAB2,
            Material.NETHER_BRICK_STAIRS,
            Material.BRICK_STAIRS,
            Material.COBBLESTONE_STAIRS,
            Material.PURPUR_STAIRS,
            Material.QUARTZ_STAIRS,
            Material.RED_SANDSTONE_STAIRS,
            Material.SANDSTONE_STAIRS,
            Material.SMOOTH_STAIRS,
            Material.STONE,
            Material.BRICK,
            Material.STONE_BUTTON,
            Material.OBSIDIAN,
            Material.OBSERVER
    ));

    public static List<Material> AXES_BLOCKS = new ArrayList<>(Arrays.asList(
            Material.COCOA,
            Material.JACK_O_LANTERN,
            Material.PUMPKIN,
            Material.VINE,
            Material.MELON_BLOCK,
            Material.BANNER,
            Material.BOOKSHELF,
            Material.CHEST,
            Material.WORKBENCH,
            Material.DAYLIGHT_DETECTOR,
            Material.DAYLIGHT_DETECTOR_INVERTED,
            Material.FENCE,
            Material.FENCE_GATE,
            Material.HUGE_MUSHROOM_1,
            Material.HUGE_MUSHROOM_2,
            Material.JUKEBOX,
            Material.LADDER,
            Material.NOTE_BLOCK,
            Material.SIGN,
            Material.SIGN_POST,
            Material.WALL_SIGN,
            Material.TRAPPED_CHEST,
            Material.WOOD,
            Material.WOOD_BUTTON,
            Material.WOODEN_DOOR,
            Material.LOG,
            Material.LOG_2,
            Material.WOOD_PLATE,
            Material.WOOD_STEP,
            Material.WOOD_DOUBLE_STEP,
            Material.BIRCH_WOOD_STAIRS,
            Material.ACACIA_STAIRS,
            Material.DARK_OAK_STAIRS,
            Material.JUNGLE_WOOD_STAIRS,
            Material.SPRUCE_WOOD_STAIRS,
            Material.WOOD_STAIRS,
            Material.TRAP_DOOR
    ));

    public static List<Material> SHOVELS_BLOCKS = new ArrayList<>(Arrays.asList(
            Material.CLAY,
            Material.DIRT,
            Material.CONCRETE_POWDER,
            Material.GRASS,
            Material.GRAVEL,
            Material.SAND,
            Material.SOUL_SAND,
            Material.SNOW,
            Material.SNOW_BLOCK
    ));

    public static List<Material> SWORDS_BLOCKS = new ArrayList<>(Arrays.asList(
            Material.WEB
    ));

}
